echo "Thurs/September 18" ; java -cp obj DateTimeParser "Thurs/September 18"
echo "Thursday, 18 September 2003" ; java -cp obj DateTimeParser "Thursday, 18 September 2003"
echo "Tuesday 16th" ; java -cp obj DateTimeParser "Tuesday 16th"
echo "Tuesday, September 16th" ; java -cp obj DateTimeParser "Tuesday, September 16th"
echo "Friday, September 12, 2003" ; java -cp obj DateTimeParser "Friday, September 12, 2003"
echo "Friday, September 12" ; java -cp obj DateTimeParser "Friday, September 12"
echo "September 19, Friday" ; java -cp obj DateTimeParser "September 19, Friday"
echo "Sept. 19" ; java -cp obj DateTimeParser "Sept. 19"
echo "Friday, Sept. 19, 2003" ; java -cp obj DateTimeParser "Friday, Sept. 19, 2003"
echo "WEDNESDAY, 24 SEPTEMBER 2003" ; java -cp obj DateTimeParser "WEDNESDAY, 24 SEPTEMBER 2003"
echo "27 November 1852" ; java -cp obj DateTimeParser "27 November 1852"
echo "Sept 18" ; java -cp obj DateTimeParser "Sept 18"
echo "Thursday, 18 September 2003" ; java -cp obj DateTimeParser "Thursday, 18 September 2003"
echo "Thursday, 18 September 2003" ; java -cp obj DateTimeParser "Thursday, 18 September 2003"
echo "Sept. 19" ; java -cp obj DateTimeParser "Sept. 19"
echo "Friday, Sept. 19, 2003" ; java -cp obj DateTimeParser "Friday, Sept. 19, 2003"
echo "September 19, Friday" ; java -cp obj DateTimeParser "September 19, Friday"
echo "Oct 3" ; java -cp obj DateTimeParser "Oct 3"
echo "October 3, Friday" ; java -cp obj DateTimeParser "October 3, Friday"
echo "WEDNESDAY, 24 SEPTEMBER 2003" ; java -cp obj DateTimeParser "WEDNESDAY, 24 SEPTEMBER 2003"
echo "27 November 1852" ; java -cp obj DateTimeParser "27 November 1852"
echo "WEDNESDAY, 24 SEPTEMBER 2003" ; java -cp obj DateTimeParser "WEDNESDAY, 24 SEPTEMBER 2003"
echo "27 November 1852" ; java -cp obj DateTimeParser "27 November 1852"
echo "Oct 3" ; java -cp obj DateTimeParser "Oct 3"
echo "Friday, October 3, 2003" ; java -cp obj DateTimeParser "Friday, October 3, 2003"
echo "9/30/03" ; java -cp obj DateTimeParser "9/30/03"
echo "Tuesday, September 30, 2003" ; java -cp obj DateTimeParser "Tuesday, September 30, 2003"
echo "Oct 3" ; java -cp obj DateTimeParser "Oct 3"
echo "October 3, Friday" ; java -cp obj DateTimeParser "October 3, Friday"
echo "Oct 16" ; java -cp obj DateTimeParser "Oct 16"
echo "Thursday, 16 October 2003" ; java -cp obj DateTimeParser "Thursday, 16 October 2003"
echo "Thursday Oct 16" ; java -cp obj DateTimeParser "Thursday Oct 16"
echo "Thursday, October 16, 2003" ; java -cp obj DateTimeParser "Thursday, October 16, 2003"
echo "Thursday Oct 16" ; java -cp obj DateTimeParser "Thursday Oct 16"
echo "Thursday, October 16, 2003" ; java -cp obj DateTimeParser "Thursday, October 16, 2003"
echo "Oct 16" ; java -cp obj DateTimeParser "Oct 16"
echo "Thursday, 16 October 2003" ; java -cp obj DateTimeParser "Thursday, 16 October 2003"
echo "Oct 16" ; java -cp obj DateTimeParser "Oct 16"
echo "Thursday, 16 October 2003" ; java -cp obj DateTimeParser "Thursday, 16 October 2003"
echo "Thursday Oct 23" ; java -cp obj DateTimeParser "Thursday Oct 23"
echo "Thursday, October 23, 2003" ; java -cp obj DateTimeParser "Thursday, October 23, 2003"
echo "Thursday Oct 23" ; java -cp obj DateTimeParser "Thursday Oct 23"
echo "Thursday, October 23, 2003" ; java -cp obj DateTimeParser "Thursday, October 23, 2003"
echo "Thursday, 16 October 2003" ; java -cp obj DateTimeParser "Thursday, 16 October 2003"
echo "Thursday, 16 October 2003" ; java -cp obj DateTimeParser "Thursday, 16 October 2003"
echo "Nov 6" ; java -cp obj DateTimeParser "Nov 6"
echo "Thursday, 6 November 2003" ; java -cp obj DateTimeParser "Thursday, 6 November 2003"
echo "Friday (Oct 24)" ; java -cp obj DateTimeParser "Friday (Oct 24)"
echo "Oct 24, Friday" ; java -cp obj DateTimeParser "Oct 24, Friday"
echo "Oct 24" ; java -cp obj DateTimeParser "Oct 24"
echo "Oct 24, Friday" ; java -cp obj DateTimeParser "Oct 24, Friday"
echo "Nov 6" ; java -cp obj DateTimeParser "Nov 6"
echo "Thursday, 6 November 2003" ; java -cp obj DateTimeParser "Thursday, 6 November 2003"
echo "November 6" ; java -cp obj DateTimeParser "November 6"
echo "Thursday, Nov. 6" ; java -cp obj DateTimeParser "Thursday, Nov. 6"
echo "Thursday, November 6, 2003" ; java -cp obj DateTimeParser "Thursday, November 6, 2003"
echo "Thursday, 4 December 2003" ; java -cp obj DateTimeParser "Thursday, 4 December 2003"
echo "Nov 7" ; java -cp obj DateTimeParser "Nov 7"
echo "Friday, November 7, 2003" ; java -cp obj DateTimeParser "Friday, November 7, 2003"
echo "November 10" ; java -cp obj DateTimeParser "November 10"
echo "November 11" ; java -cp obj DateTimeParser "November 11"
echo "Thursday, 6 November 2003" ; java -cp obj DateTimeParser "Thursday, 6 November 2003"
echo "Thursday, 6 November 2003" ; java -cp obj DateTimeParser "Thursday, 6 November 2003"
echo "Nov 7" ; java -cp obj DateTimeParser "Nov 7"
echo "Friday, November 7, 2003" ; java -cp obj DateTimeParser "Friday, November 7, 2003"
echo "MONDAY, 10 NOVEMBER 2003" ; java -cp obj DateTimeParser "MONDAY, 10 NOVEMBER 2003"
echo "November 10" ; java -cp obj DateTimeParser "November 10"
echo "November 11" ; java -cp obj DateTimeParser "November 11"
echo "Monday (11/17)" ; java -cp obj DateTimeParser "Monday (11/17)"
echo "November 17, Monday" ; java -cp obj DateTimeParser "November 17, Monday"
echo "Nov 20" ; java -cp obj DateTimeParser "Nov 20"
echo "Thursday, 20 November 2003" ; java -cp obj DateTimeParser "Thursday, 20 November 2003"
echo "Nov 20" ; java -cp obj DateTimeParser "Nov 20"
echo "Thursday, 20 November 2003" ; java -cp obj DateTimeParser "Thursday, 20 November 2003"
echo "Friday (11/21)" ; java -cp obj DateTimeParser "Friday (11/21)"
echo "November 21, Friday" ; java -cp obj DateTimeParser "November 21, Friday"
echo "Friday" ; java -cp obj DateTimeParser "Friday"
echo "November 21, Friday" ; java -cp obj DateTimeParser "November 21, Friday"
echo "Thursday, 20 November 2003" ; java -cp obj DateTimeParser "Thursday, 20 November 2003"
echo "Monday, Nov 24" ; java -cp obj DateTimeParser "Monday, Nov 24"
echo "November 24, Monday" ; java -cp obj DateTimeParser "November 24, Monday"
echo "Thursday, 4 December 2003" ; java -cp obj DateTimeParser "Thursday, 4 December 2003"
echo "Monday, Nov 24" ; java -cp obj DateTimeParser "Monday, Nov 24"
echo "November 24, Monday" ; java -cp obj DateTimeParser "November 24, Monday"
echo "Wednesday 11/26" ; java -cp obj DateTimeParser "Wednesday 11/26"
echo "November 26, 2003" ; java -cp obj DateTimeParser "November 26, 2003"
echo "Thursday and &gt;&gt;&gt;Friday December 4th &amp; 5th" ; java -cp obj DateTimeParser "Thursday and &gt;&gt;&gt;Friday December 4th &amp; 5th"
echo "12/4/03" ; java -cp obj DateTimeParser "12/4/03"
echo "Thursday/Dec 4" ; java -cp obj DateTimeParser "Thursday/Dec 4"
echo "Thursday, 4 December 2003" ; java -cp obj DateTimeParser "Thursday, 4 December 2003"
echo "Friday, Dec 5" ; java -cp obj DateTimeParser "Friday, Dec 5"
echo "December 5, 2003" ; java -cp obj DateTimeParser "December 5, 2003"
echo "Thursday/Dec 4" ; java -cp obj DateTimeParser "Thursday/Dec 4"
echo "Thursday, 4 December 2003" ; java -cp obj DateTimeParser "Thursday, 4 December 2003"
echo "Dec 16" ; java -cp obj DateTimeParser "Dec 16"
echo "Tuesday, December 16, 2003" ; java -cp obj DateTimeParser "Tuesday, December 16, 2003"
echo "Dec 12" ; java -cp obj DateTimeParser "Dec 12"
echo "Friday, December 12, 2003" ; java -cp obj DateTimeParser "Friday, December 12, 2003"
echo "Tuesday, December 9" ; java -cp obj DateTimeParser "Tuesday, December 9"
echo "Dec 12" ; java -cp obj DateTimeParser "Dec 12"
echo "Fri, 05 Dec 2003" ; java -cp obj DateTimeParser "Fri, 05 Dec 2003"
echo "Dec 12" ; java -cp obj DateTimeParser "Dec 12"
echo "Friday, December 12, 2003" ; java -cp obj DateTimeParser "Friday, December 12, 2003"
echo "Dec 16" ; java -cp obj DateTimeParser "Dec 16"
echo "Fri, 05 Dec 2003" ; java -cp obj DateTimeParser "Fri, 05 Dec 2003"
echo "Dec 16" ; java -cp obj DateTimeParser "Dec 16"
echo "Tuesday, December 16, 2003" ; java -cp obj DateTimeParser "Tuesday, December 16, 2003"
echo "January 22" ; java -cp obj DateTimeParser "January 22"
echo "Thursday, 22 January 2004" ; java -cp obj DateTimeParser "Thursday, 22 January 2004"
echo "Tuesday, 20 January 2004" ; java -cp obj DateTimeParser "Tuesday, 20 January 2004"
echo "Thurs/Jan 22" ; java -cp obj DateTimeParser "Thurs/Jan 22"
echo "Thursday, 22 January 2004" ; java -cp obj DateTimeParser "Thursday, 22 January 2004"
echo "January 21, 2004" ; java -cp obj DateTimeParser "January 21, 2004"
echo "THURSDAY" ; java -cp obj DateTimeParser "THURSDAY"
echo "Thursday, 22 January 2004" ; java -cp obj DateTimeParser "Thursday, 22 January 2004"
echo "Tuesday, Jan. 27, 2004" ; java -cp obj DateTimeParser "Tuesday, Jan. 27, 2004"
echo "Feb 6" ; java -cp obj DateTimeParser "Feb 6"
echo "Feb 6, Friday" ; java -cp obj DateTimeParser "Feb 6, Friday"
echo "Feb 12" ; java -cp obj DateTimeParser "Feb 12"
echo "Feb 12" ; java -cp obj DateTimeParser "Feb 12"
echo "Thursday, 12 February 2004" ; java -cp obj DateTimeParser "Thursday, 12 February 2004"
echo "Feb. 25, 2004" ; java -cp obj DateTimeParser "Feb. 25, 2004"
echo "Feb. 25, 2004" ; java -cp obj DateTimeParser "Feb. 25, 2004"
echo "Feb. 16" ; java -cp obj DateTimeParser "Feb. 16"
echo "Feb. 23" ; java -cp obj DateTimeParser "Feb. 23"
echo "Feb 6, Friday" ; java -cp obj DateTimeParser "Feb 6, Friday"
echo "Thursday" ; java -cp obj DateTimeParser "Thursday"
echo "Thursday" ; java -cp obj DateTimeParser "Thursday"
echo "Feb 12, Thursday" ; java -cp obj DateTimeParser "Feb 12, Thursday"
echo "Feb 12" ; java -cp obj DateTimeParser "Feb 12"
echo "Thursday, 12 February 2004" ; java -cp obj DateTimeParser "Thursday, 12 February 2004"
echo "February 17" ; java -cp obj DateTimeParser "February 17"
echo "Tuesday, 17 February 2004" ; java -cp obj DateTimeParser "Tuesday, 17 February 2004"
echo "Thursday, 12 February 2004" ; java -cp obj DateTimeParser "Thursday, 12 February 2004"
echo "Tues, Feb 17" ; java -cp obj DateTimeParser "Tues, Feb 17"
echo "Tuesday, 17 February 2004" ; java -cp obj DateTimeParser "Tuesday, 17 February 2004"
echo "Thursday, February 19" ; java -cp obj DateTimeParser "Thursday, February 19"
echo "Friday, February 20" ; java -cp obj DateTimeParser "Friday, February 20"
echo "Feb 17" ; java -cp obj DateTimeParser "Feb 17"
echo "Tuesday, 17 February 2004" ; java -cp obj DateTimeParser "Tuesday, 17 February 2004"
echo "Mar 4" ; java -cp obj DateTimeParser "Mar 4"
echo "Thursday, 4 March 2004" ; java -cp obj DateTimeParser "Thursday, 4 March 2004"
echo "Mar 4" ; java -cp obj DateTimeParser "Mar 4"
echo "Thursday, 4 March 2004" ; java -cp obj DateTimeParser "Thursday, 4 March 2004"
echo "May 2-7, 2004" ; java -cp obj DateTimeParser "May 2-7, 2004"
echo "Tuesday, March 02, 2004" ; java -cp obj DateTimeParser "Tuesday, March 02, 2004"
echo "Thursday, 4 March 2004" ; java -cp obj DateTimeParser "Thursday, 4 March 2004"
echo "May 2-7, 2004" ; java -cp obj DateTimeParser "May 2-7, 2004"
echo "5th of March, 2004" ; java -cp obj DateTimeParser "5th of March, 2004"
echo "March 5, 2004" ; java -cp obj DateTimeParser "March 5, 2004"
echo "Thursday, 4 March 2004" ; java -cp obj DateTimeParser "Thursday, 4 March 2004"
echo "May 2-7, 2004" ; java -cp obj DateTimeParser "May 2-7, 2004"
echo "March 15" ; java -cp obj DateTimeParser "March 15"
echo "March 29" ; java -cp obj DateTimeParser "March 29"
echo "April 12" ; java -cp obj DateTimeParser "April 12"
echo "April 26" ; java -cp obj DateTimeParser "April 26"
echo "May 10" ; java -cp obj DateTimeParser "May 10"
echo "March 12, 2004" ; java -cp obj DateTimeParser "March 12, 2004"
echo "Friday, March 12th, 2004" ; java -cp obj DateTimeParser "Friday, March 12th, 2004"
echo "March 25" ; java -cp obj DateTimeParser "March 25"
echo "Thursday, March 25, 2004" ; java -cp obj DateTimeParser "Thursday, March 25, 2004"
echo "March 24, 2004" ; java -cp obj DateTimeParser "March 24, 2004"
echo "Apr 15" ; java -cp obj DateTimeParser "Apr 15"
echo "Thursday, 15 April 2004" ; java -cp obj DateTimeParser "Thursday, 15 April 2004"
echo "April 1" ; java -cp obj DateTimeParser "April 1"
echo "Friday" ; java -cp obj DateTimeParser "Friday"
echo "April 9, Friday" ; java -cp obj DateTimeParser "April 9, Friday"
echo "Apr 15" ; java -cp obj DateTimeParser "Apr 15"
echo "Thursday, 15 April 2004" ; java -cp obj DateTimeParser "Thursday, 15 April 2004"
echo "Monday" ; java -cp obj DateTimeParser "Monday"
echo "Monday, April 12" ; java -cp obj DateTimeParser "Monday, April 12"
echo "Apr 15" ; java -cp obj DateTimeParser "Apr 15"
echo "Thursday, 15 April 2004" ; java -cp obj DateTimeParser "Thursday, 15 April 2004"
echo "Apr 22" ; java -cp obj DateTimeParser "Apr 22"
echo "April 15" ; java -cp obj DateTimeParser "April 15"
echo "Thursday, 22 April 2004" ; java -cp obj DateTimeParser "Thursday, 22 April 2004"
echo "Friday" ; java -cp obj DateTimeParser "Friday"
echo "April 16, Friday" ; java -cp obj DateTimeParser "April 16, Friday"
echo "Friday April 30" ; java -cp obj DateTimeParser "Friday April 30"
echo "Friday April 30th" ; java -cp obj DateTimeParser "Friday April 30th"
echo "Thursday, 15 April 2004" ; java -cp obj DateTimeParser "Thursday, 15 April 2004"
echo "Friday 16th" ; java -cp obj DateTimeParser "Friday 16th"
echo "Friday April 16th" ; java -cp obj DateTimeParser "Friday April 16th"
echo "Friday, April 23" ; java -cp obj DateTimeParser "Friday, April 23"
echo "April 23, Friday" ; java -cp obj DateTimeParser "April 23, Friday"
echo "Apr 22" ; java -cp obj DateTimeParser "Apr 22"
echo "Thursday, 22 April 2004" ; java -cp obj DateTimeParser "Thursday, 22 April 2004"
echo "Wednesday, April 21, 2004" ; java -cp obj DateTimeParser "Wednesday, April 21, 2004"
echo "Thursday, 22 April 2004" ; java -cp obj DateTimeParser "Thursday, 22 April 2004"
echo "Friday, April 23, 2004" ; java -cp obj DateTimeParser "Friday, April 23, 2004"
echo "Friday, April 23, 2004" ; java -cp obj DateTimeParser "Friday, April 23, 2004"
echo "Friday, April 23" ; java -cp obj DateTimeParser "Friday, April 23"
echo "April 23, Friday" ; java -cp obj DateTimeParser "April 23, Friday"
echo "Thursday, April 29, 2004" ; java -cp obj DateTimeParser "Thursday, April 29, 2004"
echo "Friday April 30" ; java -cp obj DateTimeParser "Friday April 30"
echo "Friday April 30th" ; java -cp obj DateTimeParser "Friday April 30th"
echo "May 7" ; java -cp obj DateTimeParser "May 7"
echo "Friday, May 7, 2004" ; java -cp obj DateTimeParser "Friday, May 7, 2004"
echo "Friday 14th" ; java -cp obj DateTimeParser "Friday 14th"
echo "Friday May 14th" ; java -cp obj DateTimeParser "Friday May 14th"
echo "May 18th" ; java -cp obj DateTimeParser "May 18th"
echo "Tuesday, May 18, 2004" ; java -cp obj DateTimeParser "Tuesday, May 18, 2004"
echo "Friday May 14" ; java -cp obj DateTimeParser "Friday May 14"
echo "Friday, May 14th" ; java -cp obj DateTimeParser "Friday, May 14th"
echo "Friday May 14th" ; java -cp obj DateTimeParser "Friday May 14th"
echo "Tuesday, May 18, 2004" ; java -cp obj DateTimeParser "Tuesday, May 18, 2004"
echo "May 12" ; java -cp obj DateTimeParser "May 12"
echo "Monday, May 17, 2004" ; java -cp obj DateTimeParser "Monday, May 17, 2004"
echo "Wednesday, May 19, 2004" ; java -cp obj DateTimeParser "Wednesday, May 19, 2004"
echo "May 17 (Wednesday)" ; java -cp obj DateTimeParser "May 17 (Wednesday)"
echo "May 18th" ; java -cp obj DateTimeParser "May 18th"
echo "Mon, 10 May 2004" ; java -cp obj DateTimeParser "Mon, 10 May 2004"
echo "May 18th" ; java -cp obj DateTimeParser "May 18th"
echo "Tuesday, May 18" ; java -cp obj DateTimeParser "Tuesday, May 18"
echo "May 12" ; java -cp obj DateTimeParser "May 12"
echo "TUESDAY MAY 25" ; java -cp obj DateTimeParser "TUESDAY MAY 25"
echo "Thursday, May 27, 2004" ; java -cp obj DateTimeParser "Thursday, May 27, 2004"
echo "May 27" ; java -cp obj DateTimeParser "May 27"
echo "*Tuesday* 25th May" ; java -cp obj DateTimeParser "*Tuesday* 25th May"
echo "*Tuesday* May 25th" ; java -cp obj DateTimeParser "*Tuesday* May 25th"
echo "Friday 28th" ; java -cp obj DateTimeParser "Friday 28th"
echo "Friday May 28th" ; java -cp obj DateTimeParser "Friday May 28th"
echo "Monday, May 24, 2004" ; java -cp obj DateTimeParser "Monday, May 24, 2004"
echo "Thursday, May 27, 2004" ; java -cp obj DateTimeParser "Thursday, May 27, 2004"
echo "Thursday, May 27, 2004" ; java -cp obj DateTimeParser "Thursday, May 27, 2004"
echo "Thursday, May 27, 2004" ; java -cp obj DateTimeParser "Thursday, May 27, 2004"
echo "May 26 (Wednesday), 2004" ; java -cp obj DateTimeParser "May 26 (Wednesday), 2004"
echo "25th May" ; java -cp obj DateTimeParser "25th May"
echo "*Tuesday* May 25th" ; java -cp obj DateTimeParser "*Tuesday* May 25th"
echo "Tuesday, May 25, 2004" ; java -cp obj DateTimeParser "Tuesday, May 25, 2004"
echo "Wednesday, May 26, 2004" ; java -cp obj DateTimeParser "Wednesday, May 26, 2004"
echo "May 26 (Wednesday), 2004" ; java -cp obj DateTimeParser "May 26 (Wednesday), 2004"
echo "Tuesday, May 25, 2004" ; java -cp obj DateTimeParser "Tuesday, May 25, 2004"
echo "Wednesday, May 26, 2004" ; java -cp obj DateTimeParser "Wednesday, May 26, 2004"
echo "May 26 (Wednesday), 2004" ; java -cp obj DateTimeParser "May 26 (Wednesday), 2004"
echo "Thursday" ; java -cp obj DateTimeParser "Thursday"
echo "Wed, 26 May 2004" ; java -cp obj DateTimeParser "Wed, 26 May 2004"
echo "Tuesday, June 01, 2004" ; java -cp obj DateTimeParser "Tuesday, June 01, 2004"
echo "Tuesday, June 01, 2004" ; java -cp obj DateTimeParser "Tuesday, June 01, 2004"
echo "Thursday, May 27, 2004" ; java -cp obj DateTimeParser "Thursday, May 27, 2004"
echo "Tuesday, June 01, 2004" ; java -cp obj DateTimeParser "Tuesday, June 01, 2004"
echo "Thursday, May 27, 2004" ; java -cp obj DateTimeParser "Thursday, May 27, 2004"
echo "Thursday, May 27, 2004" ; java -cp obj DateTimeParser "Thursday, May 27, 2004"
echo "Tuesday, June 01, 2004" ; java -cp obj DateTimeParser "Tuesday, June 01, 2004"
echo "May 27" ; java -cp obj DateTimeParser "May 27"
echo "Wed, 26 May 2004" ; java -cp obj DateTimeParser "Wed, 26 May 2004"
echo "Wed, 26 May 2004" ; java -cp obj DateTimeParser "Wed, 26 May 2004"
echo "Friday 28th" ; java -cp obj DateTimeParser "Friday 28th"
echo "Friday May 28th Tomorrow" ; java -cp obj DateTimeParser "Friday May 28th Tomorrow"
echo "Friday, February 06, 2004" ; java -cp obj DateTimeParser "Friday, February 06, 2004"
echo "Friday, May 28, 2004" ; java -cp obj DateTimeParser "Friday, May 28, 2004"
echo "Tuesday, June 01, 2004" ; java -cp obj DateTimeParser "Tuesday, June 01, 2004"
echo "Tuesday, June 01, 2004" ; java -cp obj DateTimeParser "Tuesday, June 01, 2004"
echo "Tuesday, June 01, 2004 9:45 AM" ; java -cp obj DateTimeParser "Tuesday, June 01, 2004 9:45 AM"
echo "June 14, 2004 (Monday)" ; java -cp obj DateTimeParser "June 14, 2004 (Monday)"
echo "July 6, 2004 (Tuesday)" ; java -cp obj DateTimeParser "July 6, 2004 (Tuesday)"
echo "July 7, 2004 (Wednesday)" ; java -cp obj DateTimeParser "July 7, 2004 (Wednesday)"
echo "Friday, July 09, 2004" ; java -cp obj DateTimeParser "Friday, July 09, 2004"
echo "September 24, 2004" ; java -cp obj DateTimeParser "September 24, 2004"
echo "AUGUST 30, 2004" ; java -cp obj DateTimeParser "AUGUST 30, 2004"
echo "August 30, 2004 (Monday)" ; java -cp obj DateTimeParser "August 30, 2004 (Monday)"
echo "August 13, 2004 (Friday)" ; java -cp obj DateTimeParser "August 13, 2004 (Friday)"
echo "Aug 13 Friday" ; java -cp obj DateTimeParser "Aug 13 Friday"
echo "August 13, Friday" ; java -cp obj DateTimeParser "August 13, Friday"
echo "8/13" ; java -cp obj DateTimeParser "8/13"
echo "August 13, 2004 (Friday)" ; java -cp obj DateTimeParser "August 13, 2004 (Friday)"
echo "Friday Aug 13" ; java -cp obj DateTimeParser "Friday Aug 13"
echo "Friday, Aug. 13" ; java -cp obj DateTimeParser "Friday, Aug. 13"
echo "August 13, Friday" ; java -cp obj DateTimeParser "August 13, Friday"
echo "Tuesday, August 17" ; java -cp obj DateTimeParser "Tuesday, August 17"
echo "Tuesday, August 17" ; java -cp obj DateTimeParser "Tuesday, August 17"
echo "THURSDAY, 2 SEPTEMBER 2004" ; java -cp obj DateTimeParser "THURSDAY, 2 SEPTEMBER 2004"
echo "Friday Aug 20" ; java -cp obj DateTimeParser "Friday Aug 20"
echo "Friday, Aug. 20" ; java -cp obj DateTimeParser "Friday, Aug. 20"
echo "August 20, Friday" ; java -cp obj DateTimeParser "August 20, Friday"
echo "Aug 25th" ; java -cp obj DateTimeParser "Aug 25th"
echo "Wednesday, August 25th, 2004" ; java -cp obj DateTimeParser "Wednesday, August 25th, 2004"
echo "August 26th, Thursday" ; java -cp obj DateTimeParser "August 26th, Thursday"
echo "August 26th, Thursday" ; java -cp obj DateTimeParser "August 26th, Thursday"
echo "Friday 20th August" ; java -cp obj DateTimeParser "Friday 20th August"
echo "Friday August 20th" ; java -cp obj DateTimeParser "Friday August 20th"
echo "August 30" ; java -cp obj DateTimeParser "August 30"
echo "September 24, 2004" ; java -cp obj DateTimeParser "September 24, 2004"
echo "AUGUST 30, 2004" ; java -cp obj DateTimeParser "AUGUST 30, 2004"
echo "August 30, 2004" ; java -cp obj DateTimeParser "August 30, 2004"
echo "Friday Sept. 3" ; java -cp obj DateTimeParser "Friday Sept. 3"
echo "September 3, Friday" ; java -cp obj DateTimeParser "September 3, Friday"
echo "Wednesday August 25, 2004" ; java -cp obj DateTimeParser "Wednesday August 25, 2004"
echo "Wednesday August 25, 2004" ; java -cp obj DateTimeParser "Wednesday August 25, 2004"
echo "September 2" ; java -cp obj DateTimeParser "September 2"
echo "THURSDAY, 2 SEPTEMBER 2004" ; java -cp obj DateTimeParser "THURSDAY, 2 SEPTEMBER 2004"
echo "Aug 25th" ; java -cp obj DateTimeParser "Aug 25th"
echo "Wednesday, August 25th, 2004" ; java -cp obj DateTimeParser "Wednesday, August 25th, 2004"
echo "THURSDAY, 2 SEPTEMBER 2004" ; java -cp obj DateTimeParser "THURSDAY, 2 SEPTEMBER 2004"
echo "Sep 23, Thursday" ; java -cp obj DateTimeParser "Sep 23, Thursday"
echo "September 23, Thursday" ; java -cp obj DateTimeParser "September 23, Thursday"
echo "Thursday, Sept. 23" ; java -cp obj DateTimeParser "Thursday, Sept. 23"
echo "September 23 (Thursday)" ; java -cp obj DateTimeParser "September 23 (Thursday)"
echo "Friday September 24" ; java -cp obj DateTimeParser "Friday September 24"
echo "Friday September 24" ; java -cp obj DateTimeParser "Friday September 24"
echo "Oct 1, Friday" ; java -cp obj DateTimeParser "Oct 1, Friday"
echo "October 1, Friday" ; java -cp obj DateTimeParser "October 1, Friday"
echo "Oct 1, Friday" ; java -cp obj DateTimeParser "Oct 1, Friday"
echo "October 1, Friday" ; java -cp obj DateTimeParser "October 1, Friday"
echo "9/28/2004" ; java -cp obj DateTimeParser "9/28/2004"
echo "Sep 21, 2004" ; java -cp obj DateTimeParser "Sep 21, 2004"
echo "Wed Oct 6" ; java -cp obj DateTimeParser "Wed Oct 6"
echo "Wednesday, October 6" ; java -cp obj DateTimeParser "Wednesday, October 6"
echo "October 7" ; java -cp obj DateTimeParser "October 7"
echo "Thursday" ; java -cp obj DateTimeParser "Thursday"
echo "Thursday, October 7" ; java -cp obj DateTimeParser "Thursday, October 7"
echo "October 13, 2004" ; java -cp obj DateTimeParser "October 13, 2004"
echo "10-13-04" ; java -cp obj DateTimeParser "10-13-04"
echo "Wed, 13 Oct 2004" ; java -cp obj DateTimeParser "Wed, 13 Oct 2004"
echo "10-13-04" ; java -cp obj DateTimeParser "10-13-04"
echo "Wednesday, October 13, 2004" ; java -cp obj DateTimeParser "Wednesday, October 13, 2004"
echo "Wed Oct 20" ; java -cp obj DateTimeParser "Wed Oct 20"
echo "Wednesday, October 20, 2004" ; java -cp obj DateTimeParser "Wednesday, October 20, 2004"
echo "11/18" ; java -cp obj DateTimeParser "11/18"
echo "Nov. 19" ; java -cp obj DateTimeParser "Nov. 19"
echo "11/18" ; java -cp obj DateTimeParser "11/18"
echo "Thu, 21 Oct 2004" ; java -cp obj DateTimeParser "Thu, 21 Oct 2004"
echo "11/18" ; java -cp obj DateTimeParser "11/18"
echo "November 18" ; java -cp obj DateTimeParser "November 18"
echo "Friday" ; java -cp obj DateTimeParser "Friday"
echo "November 5, 2004" ; java -cp obj DateTimeParser "November 5, 2004"
echo "Friday" ; java -cp obj DateTimeParser "Friday"
echo "Friday, November 5" ; java -cp obj DateTimeParser "Friday, November 5"
echo "11/2" ; java -cp obj DateTimeParser "11/2"
echo "11/9" ; java -cp obj DateTimeParser "11/9"
echo "11/12" ; java -cp obj DateTimeParser "11/12"
echo "November 2" ; java -cp obj DateTimeParser "November 2"
echo "11/2" ; java -cp obj DateTimeParser "11/2"
echo "11/2" ; java -cp obj DateTimeParser "11/2"
echo "11/9" ; java -cp obj DateTimeParser "11/9"
echo "Mon, 2004-11-01" ; java -cp obj DateTimeParser "Mon, 2004-11-01"
echo "11/9" ; java -cp obj DateTimeParser "11/9"
echo "11/12" ; java -cp obj DateTimeParser "11/12"
echo "November 2" ; java -cp obj DateTimeParser "November 2"
echo "Friday (Nov 5)" ; java -cp obj DateTimeParser "Friday (Nov 5)"
echo "November 5, Friday" ; java -cp obj DateTimeParser "November 5, Friday"
echo "11/18" ; java -cp obj DateTimeParser "11/18"
echo "November 18" ; java -cp obj DateTimeParser "November 18"
echo "Friday, Nov 19" ; java -cp obj DateTimeParser "Friday, Nov 19"
echo "Friday, Nov 19" ; java -cp obj DateTimeParser "Friday, Nov 19"
echo "November 19, Friday" ; java -cp obj DateTimeParser "November 19, Friday"
echo "November 19, Friday" ; java -cp obj DateTimeParser "November 19, Friday"
echo "November 19, Friday" ; java -cp obj DateTimeParser "November 19, Friday"
echo "November 19, Friday" ; java -cp obj DateTimeParser "November 19, Friday"
echo "Wed, Jan 19" ; java -cp obj DateTimeParser "Wed, Jan 19"
echo "Wednesday, January 19, 2005" ; java -cp obj DateTimeParser "Wednesday, January 19, 2005"
echo "Wed, Jan 19" ; java -cp obj DateTimeParser "Wed, Jan 19"
echo "Wednesday, January 19, 2005" ; java -cp obj DateTimeParser "Wednesday, January 19, 2005"
echo "Wed, Jan 19" ; java -cp obj DateTimeParser "Wed, Jan 19"
echo "January 17, 2005" ; java -cp obj DateTimeParser "January 17, 2005"
echo "Wed, Jan 19" ; java -cp obj DateTimeParser "Wed, Jan 19"
echo "Wednesday, January 19" ; java -cp obj DateTimeParser "Wednesday, January 19"
echo "Monday, January 17, 2005" ; java -cp obj DateTimeParser "Monday, January 17, 2005"
echo "Wed, Jan 19" ; java -cp obj DateTimeParser "Wed, Jan 19"
echo "Wednesday, January 19, 2005" ; java -cp obj DateTimeParser "Wednesday, January 19, 2005"
echo "Jan 31,05" ; java -cp obj DateTimeParser "Jan 31,05"
echo "Monday 02/14" ; java -cp obj DateTimeParser "Monday 02/14"
echo "Friday, February 11, 2005" ; java -cp obj DateTimeParser "Friday, February 11, 2005"
echo "Monday 02/14" ; java -cp obj DateTimeParser "Monday 02/14"
echo "Monday 02/14" ; java -cp obj DateTimeParser "Monday 02/14"
echo "February 14" ; java -cp obj DateTimeParser "February 14"
